export { default as light } from "./light.png"
export { default as lightGreen } from "./light_green.png"
export { default as lightGray } from "./light_gray.png"
export { default as dark } from "./dark.png"
export { default as darkBlue } from "./dark_blue.png"
export { default as darkGray } from "./dark_gray.png"
export { default as darkPurple } from "./dark_purple.png"